version: "3.9"

services:
  auth-db:
    image: postgres:15-alpine
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 0248qazwsx
      POSTGRES_DB: auth_db
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-service:
    build:
      context: .
      dockerfile: auth-service/dockerfile
    container_name: auth-service
    depends_on:
      auth-db:
        condition: service_healthy
    env_file:
      - ./auth-service/.env
    ports:
      - "3001:3000"
    restart: always

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/dockerfile
    container_name: api-gateway
    depends_on:
      - auth-service
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: always

volumes:
  auth-db-data: