name: Build & Push Docker Images

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build auth-service
        run: docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/auth-service:latest \
            -f auth-service/dockerfile \
            .
      - name: Build api-gateway
        run: docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest \
            -f auth-service/dockerfile \
            .

      - name: Push auth-service
        run: docker push ${{ secrets.DOCKER_USERNAME }}/auth-service:latest

      - name: Push api-gateway
        run: docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest
